# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
openapi: 3.0.3
info:
  title: Region Analytics API
  description: |
    A service that consumes the AI Workflow for restricted regions, and will generate
    alerts given triggers defined through this API. This service is specialized to identify
    people and their foot positions within a monitor, and detect if they are within
    a defined region.

    Alerts will be triggered at most once per second. Alert history is stored by the
    service and can be queried through this API by polling alerts.

    As an example, to get started on a Region alert, a client would:
    * POST to /config/region to define a region within a monitor.
    * POST to /config/alerts/region to define a new trigger to generate alerts.
    * Periodically GET from /alerts/region to observe new alerts.

  contact:
    name: Qualcomm Support Forums
    url: https://mysupport.qualcomm.com/supportforums/s/
  license:
    name: BSD-3-Clause-Clear
  version: '1.0.0'
servers:
  - url: https://{device-address}/region-analytics/v1/api
    description: Server URL
    variables:
      device-address:
        description: IP address (and port) of the host of the Region Analytics API ingress.
        default: your.device.ip.here:8080

x-string-constants:
  - timestamp:       &TIMESTAMP_EXAMPLE   1729118760.000 # Epoch time in seconds. May optionally provide fractional seconds
  - later_timestamp: &TIMESTAMP_2_EXAMPLE 1729118780.999 # A later time; example shows 999 milliseconds past the second.
  - monitor: &MONITOR_ID_EXAMPLE "camera1"
  - region_id: &REGION_ID_EXAMPLE "{unique-region-id}"
  - trigger_id: &TRIGGER_ID_EXAMPLE "{unique-trigger-id}"

tags: 
  - name: alerts
    description: Poll historical alerts
  - name: config
    description: Configure regions and triggers that generate alerts from regions
  - name: util
    description: Utility APIs
security: []
paths:
  /healthz:
    get:
      tags:
        - util
      summary: Check server health
      description: Responds health of the server and its connections.
      operationId: getHealth
      responses:
        '200':
          description: OK
        '501':
          description: Server unhealthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Health        

  /config/region:
    post:
      tags:
        - config
      summary: Create a new region
      description: Create a region that can be addressed by alerts
      operationId: configRegionCreate
      requestBody:
        description: |
          Define a new region in a monitor by giving the coordinates of its vertices.

          A region is a polygon of at least two vertices. The `coordinates` field is a
          list of `Coord` {x,y} objects that define the vertices of a polygon. The values
          of x and y range from 0.0 to 1.0, with {x: 0.0, y: 0.0} defined as the top-left
          corner of the monitor.
          
          The region is interpreted as a polygon whose edges connect `coordinates[0..N]` like so:
          - The first edge is the line from `coordinates[0]` to `coordinates[1]`.
          - The next edge is the line from `coordinates[1]` to `coordinates[2]`.
          - ...
          - The penultimate edge is the line from `coordinates[N-1]` to `coordinates[N]`.
          - The final edge is the line from `coordinates[N]` to `coordinates[0]`, closing
            the polygon.

          Legal regions:
          - Must have at least two vertices.
          - Must not have crossing lines, including the final line from vertex N to vertex 0.

        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Region'
            examples:
              Top-left triangle:
                $ref: '#/components/examples/regionTopLeftTriangle'
              Bottom-right quadrant:
                $ref: '#/components/examples/regionBottomRightQuadrant'
              ILLEGAL!! Two-vertex non-region:
                $ref: '#/components/examples/illegalRegionTwoVertex'
              ILLEGAL!! Region with intersecting lines:
                $ref: '#/components/examples/illegalRegionIntersecting'
              
      responses:
        '200':
          description: New region was successfully configured.
        default:
          description: Error configuring region.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegion        
    delete:
      tags:
        - config
      summary: Delete region
      description: Deletes an existing region by region ID.
      operationId: configRegionDelete
      parameters:
      - name: regionId
        in: query          
        required: true
        description: Region ID to delete.
        schema:
          type: string
          example: *REGION_ID_EXAMPLE
      responses:
        '200':
          description: Region was successfully deleted.
        default:
          description: Error deleting region.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegion        
    get:
      tags:
        - config
      summary: Get regions
      description: Return list of regions on a given monitor ID.
      operationId: configRegionGet
      parameters:
      - name: monitorId
        in: query          
        required: true
        description: Monitor ID whose regions are listed.
        schema:
          type: string
          example: *MONITOR_ID_EXAMPLE
      responses:
        '200':
          description: List of regions in response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Regions'
        default:
          description: Error getting regions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegion

  /config/alerts/region:
    post:
      tags:
        - config
      summary: Configure a new trigger to generate alerts on region
      description: Configures a new trigger attached to a region which will generate alerts given conditions.
      operationId: configTriggerRegionCreate
      requestBody:
        description: |
          Defines the region and conditions on which to trigger an alert.

          Triggers are attached to regions by `region_id`, with a client-provided globally-
          unique identifier (`trigger_id`) and a human-readable name `trigger_name` to
          describe the reason for the trigger.

          The `trigger_condition` defines when a trigger generates alerts:
            * 'occupancy_changed': Alert whenever number of persons in region changes. Use to see all occupancy changes.
            * 'occupancy_over': Alert when an occupancy increase crosses over a limit. Use when there's a maximum amount of people expected in a region.
            * 'occupancy_under': Alert when an occupancy decrease crosses under a limit. Use when there's at least some number of people expected in a region.

          The 'occupancy_changed' condition will trigger whenever there's a change of
          occupancy in the region, and does not require `params`.

          The 'occupancy_over' and 'occupancy_under' conditions require a `params` of
          `["name": "threshold", "value": "<count>"]`, where '<count>' is the numeric threshold for the over
          or under. For example, a trigger with 'occupancy_over' with a threshold of "3"
          will generate an alert when the occupancy becomes _greater than_ 3. The alert won't
          be triggered again until the occupancy crosses back over the threshold.
          The "params" field depends on the trigger condition selected.
          
          See the examples below for different trigger conditions and their required "params".          

        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trigger'
            examples:
              Occupancy Over:
                $ref: '#/components/examples/triggerOccupancyOver'
              Occupancy Under:
                $ref: '#/components/examples/triggerOccupancyUnder'
              Occupancy Changed:
                $ref: '#/components/examples/triggerOccupancyChanged'
              
      responses:
        '200':
          description: New trigger was successfully configured.
        default:
          description: Error configuring trigger.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegionTrigger        
    delete:
      tags:
        - config
      summary: Delete trigger
      description: Deletes an existing trigger by trigger ID.
      operationId: configTriggerRegionDelete
      parameters:
      - name: triggerId
        in: query          
        required: true
        description: Trigger ID to delete.
        schema:
          type: string
          example: *TRIGGER_ID_EXAMPLE
      responses:
        '200':
          description: Trigger was successfully deleted.
        '400':
          description: Error delting trigger.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegionTrigger        
    get:
      tags:
        - config
      summary: Get triggers
      description: Return list of triggers on a given monitor ID.
      operationId: configTriggerRegionGet
      parameters:
      - name: monitorId
        in: query          
        required: true
        description: Monitor ID whose triggers are listed.
        schema:
          type: string
          example: *MONITOR_ID_EXAMPLE
      responses:
        '200':
          description: List of triggers in response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Triggers'
        '400':
          description: Error deleting trigger.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigRegionTrigger

  /alerts/region:
    get:
      tags:
        - alerts
      summary: Get all alerts
      description: Return all alerts from a list of monitors.
      operationId: getAllRegionAlerts
      parameters:
        - name: monitorIds
          in: query          
          required: true
          description: Alerts on these monitors are returned.
          schema:
            type: array
            items:
              type: string
              example: *MONITOR_ID_EXAMPLE
          
        - name: fromTime
          in: query          
          required: true
          description: Earliest alert to return
          schema:
            type: number
            format: double
            example: *TIMESTAMP_EXAMPLE
        - name: toTime
          in: query          
          required: true
          description: Latest alert to return
          schema:
            type: number
            format: double
            example: *TIMESTAMP_2_EXAMPLE

      responses:
        '200':
          description: Response contains alerts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alerts'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: RegionAlert


components:
  
  schemas:
    
    Alert:
      description: Information about an alert that has been generated by a configured Trigger.
      type: object
      properties:
        monitor_id:
          description: Monitor corresponding to this alert.
          type: string
          example: *MONITOR_ID_EXAMPLE
        source_trigger:
            $ref: "#/components/schemas/Trigger"
        time:
          description: Timestamp at which alert was generated.
          type: number
          format: double
          example: *TIMESTAMP_EXAMPLE
        occupants:
          description: List of occupants within region at time of trigger.
          type: array
          items:
            $ref: "#/components/schemas/Occupant"
      required:
        - monitor_id
        - source_trigger
        - time
    
    Alerts:
      description: List of Alert objects
      type: array
      items:
        $ref: "#/components/schemas/Alert"
        
    Occupant:
      description: A person in the scene.
      type: object
      properties:
        bounding_box:
          $ref: "#/components/schemas/BoundingBox"

    BoundingBox:
      description: Describe rectangular area by top-left and bottom-right coordinates.
      type: object
      properties:
        top_left:
          $ref: "#/components/schemas/Coord"
        bottom_right:
          $ref: "#/components/schemas/Coord"
      example:
        top_left:
          x: 0.2
          y: 0.3
        bottom_right:
          x: 0.4
          y: 0.5

    Coord:
      description: Coordinate in a monitor
      type: object
      properties:
        x:
          type: number
          format: double
          description: From 0.0 (left side of monitor) to 1.0 (right side of monitor)
          example: 0.5
        y:
          type: number
          format: double
          description: From 0.0 (top of monitor) to 1.0 (bottom of monitor)
          example: 0.5

    Region:
      description: Defines a region of a monitor.
      type: object
      properties:
        monitor_id:
          description: Monitor on which to place region.
          type: string
          example: *MONITOR_ID_EXAMPLE
        region_id:
          description: Globally-unique identifier used when referring to region.
          type: string
          example: *REGION_ID_EXAMPLE
        region_name:
          description: Human-readable name for the region.
          type: string
          example: "Restricted zone near conveyer belt"
        coordinates:
          description: List of vertices that define bounds of region.
          type: array
          items:
            $ref: "#/components/schemas/Coord"
    
    Regions:
      description: List of Region objects
      type: array
      items:
        $ref: "#/components/schemas/Region"

    Trigger:
      description: |
        Definition of a trigger. See POST /config/alerts/region for details.

      type: object
      properties:
        region_id:
          description: Region on which to place trigger.
          type: string
          example: *REGION_ID_EXAMPLE
        trigger_id:
          description: Globally-unique identifier used when referring to trigger.
          type: string
          example: *TRIGGER_ID_EXAMPLE
        trigger_name:
          description: Human-readable name for the trigger.
          type: string
          example: "Person nearing conveyer belt."
        trigger_condition:
          type: string
          description: When this trigger should generate alerts. See request body description.
          enum: ["occupancy_changed", "occupancy_over", "occupancy_under"]
          example: occupancy_over
        params:
          description: List of parameters required to configure alert. Depends on `trigger_condition`
          type: array
          items:
            $ref: "#/components/schemas/Param"
          example:
            - name: "threshold"
              value: "3"
      required:
        - region_id
        - trigger_id
        - trigger_name
        - trigger_condition
    
    Triggers:
      description: List of Trigger objects
      type: array
      items:
        $ref: "#/components/schemas/Trigger"

    Param:
      description: Generic name, value pair for parameters or settings.
      type: object

      properties:
        name:
          description: Name of parameter.
          type: string
          example: "parameter_name"
        value:
          description: Value of parameter.
          type: string
          example: "parameter_value_string"

    Error:
      description: "Error response"
      type: object
      properties:
        reason:
          type: string
          description: Detailed reason for error.
          example: "Invalid user input in parameter..(etc.)"

  examples:

    regionTopLeftTriangle:
      value:
        monitor_id: *MONITOR_ID_EXAMPLE
        region_id: *REGION_ID_EXAMPLE
        region_name: "Triangle covering top-left diagonal half of monitor"
        coordinates:
          - x: 0.0 # top-left
            y: 0.0
          - x: 1.0 # top-right
            y: 0.0
          - x: 0.0 # bottom-left
            y: 1.0

    regionBottomRightQuadrant:
      value:
        monitor_id: *MONITOR_ID_EXAMPLE
        region_id: *REGION_ID_EXAMPLE
        region_name: "Square covering bottom-right quadrant of monitor"
        coordinates:
          - x: 0.5 # middle of monitor = top-left of quadrant
            y: 0.5
          - x: 1.0 # middle-right of monitor = top-right of quadrant
            y: 0.5
          - x: 1.0 # bottom-right of monitor = bottom-right of quadrant
            y: 1.0
          - x: 0.5 # bottom-middle of monitor = bottom-left of quadrant
            y: 1.0

    illegalRegionTwoVertex:
      value:
        monitor_id: *MONITOR_ID_EXAMPLE
        region_id: *REGION_ID_EXAMPLE
        region_name: "ILLEGAL!! Only has 2 vertices, does not describe region"
        coordinates:
          - x: 0.1
            y: 0.2
          - x: 0.3
            y: 0.4

    illegalRegionIntersecting:
      value:
        monitor_id: *MONITOR_ID_EXAMPLE
        region_id: *REGION_ID_EXAMPLE
        region_name: "ILLEGAL!! Line between vertices 0 and 1 is crossed by line between vertices 2 and 3"
        coordinates:
          - x: 0.0 # middle-left...
            y: 0.5
          - x: 1.0 # to middle-right = horizonal line across monitor.
            y: 0.5
          - x: 0.5 # bottom-middle..
            y: 1.0
          - x: 0.5 # ..to top-middle = vertical line across monitor, crossing horizontal line.
            y: 0.0

    triggerOccupancyOver:
      value:
        region_id: *REGION_ID_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Trigger an alert whenever occupancy changes from <= 2 to >= 3."
        trigger_condition: "occupancy_over"
        params:
          - name: "threshold"
            value: "2"

    triggerOccupancyUnder:
      value:
        region_id: *REGION_ID_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Trigger an alert whenever occupancy changes from >= 3 to <= 2."
        trigger_condition: "occupancy_under"
        params:
          - name: "threshold"
            value: "3"

    triggerOccupancyChanged:
      value:
        region_id: *REGION_ID_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Alert each time occupancy changes in region; no params needed."
        trigger_condition: "occupancy_changed"


