# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
openapi: 3.0.3
info:
  title: People Analytics API
  description: |
    A service that consumes the AI Workflow for object detection, and will generate alerts
    given triggers defined through this API. This service is specialized to analyze
    people including people counting, occupancy analytics, and objects attached-to
    or carried-by people, known as "accessories".

    Alerts will be triggered at most once per second. Alert history is stored
    by the service and can be queried through this API by polling alerts.

    As an example, to get started on an FOV alert, a client would:
    * POST to /config/alerts/fov to create a new trigger to generate alerts.
    * Periodically GET from /alerts/fov to observe new alerts.

  contact:
    name: Qualcomm Support Forums
    url: https://mysupport.qualcomm.com/supportforums/s/
  license:
    name: BSD-3-Clause-Clear
  version: '1.0.3'
servers:
  - url: https://{device-address}/people-analytics/v1/api
    description: Server URL
    variables:
      device-address:
        description: IP address (and port) of the host of the People Analytics API ingress.
        default: your.device.ip.here:8080

x-string-constants:
  - timestamp:       &TIMESTAMP_EXAMPLE   1729118760.000 # Epoch time in seconds. May optionally provide fractional seconds
  - later_timestamp: &TIMESTAMP_2_EXAMPLE 1729118780.999 # A later time; example shows 999 milliseconds past the second.
  - monitor: &MONITOR_EXAMPLE "camera1"
  - trigger_id: &TRIGGER_ID_EXAMPLE "{unique-trigger-id}"
  - alert_uuid: &ALERT_UUID_EXAMPLE "{unique-alert-uuid}"

tags:
  - name: alerts
    description: Poll historical alerts
  - name: config
    description: Configure triggers which generate alerts as well as microservice settings
  - name: analytics
    description: Query analytics data
  - name: health
    description: Health checks for API service.
security: []
paths:
  /alerts/fov:
    get:
      tags:
        - alerts
      summary: Get all alerts
      description: |
        Return all alerts from a list of monitors.

        The `trigger_condition` defines when a trigger generates alerts.

        See examples below for different trigger_conditions and the data that is in the message.
      operationId: getAllAlerts
      parameters:
        - name: monitorIds
          in: query
          required: true
          description: Alerts on these monitors are returned.
          schema:
            type: array
            items:
              type: string
              example: *MONITOR_EXAMPLE

        - name: fromTime
          in: query
          required: true
          description: Earliest alert to return
          schema:
            type: number
            format: double
            example: *TIMESTAMP_EXAMPLE
        - name: toTime
          in: query
          required: true
          description: Latest alert to return
          schema:
            type: number
            format: double
            example: *TIMESTAMP_2_EXAMPLE

      responses:
        '200':
          description: List of All types of alerts in response sorted by time.
          content:
            accessories:
              schema:
                $ref: '#/components/schemas/Alerts'
            occupancy:
              schema:
                $ref: '#/components/schemas/AlertsOccupancy'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: AlertFov

  /config/alerts/fov:
    post:
      tags:
        - config
      summary: Configure triggers which generate alerts
      description: Configures a new trigger attached to monitor which will generate alerts given conditions.
      operationId: configTrigger
      requestBody:
        description: |
          Creates a new trigger attached to the specified monitor. When trigger conditions are matched,
          an alert will be generated.

          Triggers are defined by a client-provided globally-unique identifier (`trigger_id`)
          and a human-readable name `trigger_name` to describe the reason for the trigger.

          The `trigger_condition` defines when a trigger generates alerts:
            * 'required_accessories': Alert if person is present missing one or more of required accesseries.
            * 'restricted_accessories': Alert if person is present with any restricted accessory.
            * 'occupancy_changed': Alert whenever number of persons in frame changes. Use to see all occupancy changes.
            * 'occupancy_over': Alert when an occupancy increase crosses over a limit. Use when there's a maximum amount of people expected in a frame.
            * 'occupancy_under': Alert when an occupancy decrease crosses under a limit. Use when there's at least some number of people expected in a frame.
            * 'loitering_over': Alert when an occupant's dwell time within the screen crosses over a limit (in seconds).

          The 'occupancy_changed' condition will trigger whenever there's a change of
          occupancy in the frame, and does not require `params`.

          The 'occupancy_over' and 'occupancy_under' conditions require a `params` of
          `["name": "threshold", "value": "<count>"]`, where '<count>' is the numeric threshold for the over
          or under. For example, a trigger with 'occupancy_over' with a threshold of "3"
          will generate an alert when the occupancy becomes _greater than_ 3. The alert won't
          be triggered again until the occupancy crosses back over the threshold.
          The "params" field depends on the trigger condition selected.

          The 'loitering_over' condition require a `params` of
          `["name": "threshold", "value": "<value>"]`, where '<value>' is the numeric threshold for the over.
          For example, a trigger with 'loitering_over' with a threshold of "300000" (5 minutes)
          will generate an alert when the occupant's dwell time within the given monitor
          becomes _greater than_ 300000.

          See the examples below for different trigger conditions and their required "params".

        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trigger'
            examples:
              Required Accessories:
                $ref: '#/components/examples/triggerExampleRequiredAccessories'
              Restricted Accessories:
                $ref: '#/components/examples/triggerExampleRestrictedAccessories'
              Occupancy Over:
                $ref: '#/components/examples/triggerOccupancyOver'
              Occupancy Under:
                $ref: '#/components/examples/triggerOccupancyUnder'
              Occupancy Changed:
                $ref: '#/components/examples/triggerOccupancyChanged'
              Loitering Over:
                $ref: '#/components/examples/triggerLoiteringOver'

      responses:
        '200':
          description: New trigger was successfully configured.
        '400':
          description: Error configuring trigger.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigFovTrigger
    delete:
      tags:
        - config
      summary: Delete trigger
      description: Deletes an existing trigger by trigger ID.
      operationId: deleteTrigger
      parameters:
      - name: triggerId
        in: query
        required: true
        description: Trigger ID to delete.
        schema:
          type: string
          example: *TRIGGER_ID_EXAMPLE
      responses:
        '200':
          description: Trigger was successfully deleted.
        '400':
          description: Error delting trigger.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigFovTrigger
    get:
      tags:
        - config
      summary: Get triggers
      description: Return list of triggers on a given monitor ID.
      operationId: getTriggers
      parameters:
      - name: monitorId
        in: query
        required: true
        description: Monitor ID whose triggers are listed.
        schema:
          type: string
          example: *MONITOR_EXAMPLE
      responses:
        '200':
          description: List of triggers in response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Triggers'
        '400':
          description: Error getting triggers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: ConfigFovTrigger

  /analytics/count/fov:
    get:
      tags:
        - analytics
      summary: Query occupancy statistics within timeframe.
      description: |
        Returns the occupancy statistics for the timeframe specified.

        The minimum Interval is 5minutes.
      operationId: getAnalyticsCount
      parameters:
        - name: monitorId
          in: query
          required: true
          description: Statistics from this monitor is returned.
          schema:
            type: string
            example: *MONITOR_EXAMPLE
        - name: fromTime
          in: query
          required: true
          description: Start of timeframe
          schema:
            type: number
            format: double
            example: *TIMESTAMP_EXAMPLE
        - name: toTime
          in: query
          required: true
          description: End of timeframe
          schema:
            type: number
            format: double
            example: *TIMESTAMP_2_EXAMPLE
      responses:
        '200':
          description: Occupancy statistics within the given timeframe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OccupancyCount'
        '400':
          description: Error retrieving value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: AnalyticsFovCount


  /analytics/heatmap/fov:
    get:
      tags:
        - analytics
      summary: Query occupancy heatmap within timeframe.
      description: |
         The heatmap is specified in a 64x64 2D array.

         The minimum Interval is 5minutes.

      operationId: getAnalyticsCount
      parameters:
        - name: monitorId
          in: query
          required: true
          description: Statistics from this monitor is returned.
          schema:
            type: string
            example: *MONITOR_EXAMPLE
        - name: fromTime
          in: query
          required: true
          description: Start of timeframe
          schema:
            type: number
            format: double
            example: *TIMESTAMP_EXAMPLE
        - name: toTime
          in: query
          required: true
          description: End of timeframe
          schema:
            type: number
            format: double
            example: *TIMESTAMP_2_EXAMPLE
      responses:
        '200':
          description: Occupancy heatmap within the given timeframe, specified in a row x col 2D array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OccupancyHeatmap'
        '400':
          description: Error retrieving value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: AnalyticsFovHeatmap

  /health:
    get:
      tags:
        - health
      summary: Health Check
      description: Health Check
      operationId: getHealth
      responses:
        '200':
          description: Successful health;
        '405':
          description: Invalid input
      x-swagger-router-controller: Health

components:

  schemas:

    Alert:
      description: Information about an alert that has been generated by a configured Trigger.
      type: object
      properties:
        source_trigger:
          $ref: "#/components/schemas/Trigger"
        alert_id:
          description: Alert identifier
          type: string
          format: uuid
          example: *ALERT_UUID_EXAMPLE
        time:
          description: Timestamp at which alert was generated.
          type: number
          format: double
          example: *TIMESTAMP_EXAMPLE
        end_time:
          description: Timestamp at which alert was cleared. Not included if alert has not cleared.
          format: double
          example: *TIMESTAMP_2_EXAMPLE
        type:
          description: Alert type
          type: string
          enum: ["accessories", "occupancy"]
          example: accessories
        causes:
          description: List of people by bounding box, and what accessories are in violation.
          type: array
          items:
            type: object
            properties:
              accessories:
                type: string
                example: "helmet, glove"
              violator:
                $ref: "#/components/schemas/BoundingBox"

    AlertOccupancy:
      description: Information about an alert that has been generated by a configured Trigger.
      type: object
      properties:
        source_trigger:
          $ref: '#/components/schemas/TriggerOccupancy'
        alert_id:
          description: Alert identifier
          type: string
          format: uuid
          example: *ALERT_UUID_EXAMPLE
        time:
          description: Timestamp at which alert was generated.
          type: number
          format: double
          example: *TIMESTAMP_EXAMPLE
        end_time:
          description: Timestamp at which alert was cleared. Not included if alert has not cleared.
          format: double
          example: *TIMESTAMP_2_EXAMPLE
        type:
          description: Alert type
          type: string
          enum: ["accessories", "occupancy"]
          example: occupancy
        occupants:
          description: List of occupants within frame at time of trigger.
          type: array
          items:
            $ref: "#/components/schemas/Occupant"

    Alerts:
      description: List of Alert objects
      type: array
      items:
        $ref: "#/components/schemas/Alert"

    AlertsOccupancy:
      description: List of Alert objects
      type: array
      items:
        $ref: "#/components/schemas/AlertOccupancy"

    BoundingBox:
      description: Describe rectangular area by top-left and bottom-right coordinates.
      type: object
      properties:
        top_left:
          $ref: "#/components/schemas/Coord"
        bottom_right:
          $ref: "#/components/schemas/Coord"
      example:
        top_left:
          x: 0.2
          y: 0.3
        bottom_right:
          x: 0.4
          y: 0.5

    Coord:
      description: Coordinate in a monitor
      type: object
      properties:
        x:
          type: number
          format: double
          description: From 0.0 (left side of monitor) to 1.0 (right side of monitor)
          example: 0.5
        y:
          type: number
          format: double
          description: From 0.0 (top of monitor) to 1.0 (bottom of monitor)
          example: 0.5

    Trigger:
      description: Monitor and conditions on which to trigger an alert.
      type: object
      properties:
        monitor_id:
          description: Monitor on which to place trigger.
          type: string
          example: *MONITOR_EXAMPLE
        trigger_id:
          description: Globally-unique identifier used when referring to trigger.
          type: string
          example: *TRIGGER_ID_EXAMPLE
        trigger_name:
          description: Human-readable name for the trigger.
          type: string
          example: "Person lacking hemlet, goggles, or gloves."
        trigger_condition:
          type: string
          description: >
            When this trigger should generate alerts.

            Types of conditions:
             * `required_accessories` - Alert if person is present missing one or more of required accesseries.
             * `restricted_accessories` - Alert if person is present with any restricted accessory.
             * 'occupancy_changed': Alert whenever number of persons in frame changes. Use to see all occupancy changes.
             * 'occupancy_over': Alert when an occupancy increase crosses over a limit. Use when there's a maximum amount of people expected in a frame.
             * 'occupancy_under': Alert when an occupancy decrease crosses under a limit. Use when there's at least some number of people expected in a frame.
             * 'loitering_over': Alert when an occupant's dwell time within the given monitor crosses over a limit (in seconds).
          enum: ["required_accessories", "restricted_accessories", "occupancy_changed", "occupancy_over", "occupancy_under", "loitering_over"]
          example: required_accessories
        params:
          description: List of parameters required to configure alert.
          type: array
          items:
            $ref: "#/components/schemas/Param"
          example:
            - name: "accessories"
              value: "helmet, goggles, glove"
      required:
        - monitor_id
        - trigger_id
        - trigger_name
        - trigger_condition

    TriggerOccupancy:
      description: Monitor and conditions on which to trigger an alert.
      type: object
      properties:
        monitor_id:
          description: Monitor on which to place trigger.
          type: string
          example: *MONITOR_EXAMPLE
        trigger_id:
          description: Globally-unique identifier used when referring to trigger.
          type: string
          example: *TRIGGER_ID_EXAMPLE
        trigger_name:
          description: Human-readable name for the trigger.
          type: string
          example: "Person lacking hemlet, goggles, or gloves."
        trigger_condition:
          type: string
          description: >
            When this trigger should generate alerts.

            Types of conditions:
             * 'occupancy_changed': Alert whenever number of persons in frame changes. Use to see all occupancy changes.
             * 'occupancy_over': Alert when an occupancy increase crosses over a limit. Use when there's a maximum amount of people expected in a frame.
             * 'occupancy_under': Alert when an occupancy decrease crosses under a limit. Use when there's at least some number of people expected in a frame.
             * 'loitering_over': Alert when an occupant's dwell time within the given monitor crosses over a limit (in seconds).
          enum: ["required_accessories", "restricted_accessories", "occupancy_changed", "occupancy_over", "occupancy_under", "loitering_over"]
          example: "occupancy_over"
        params:
          description: List of parameters required to configure alert.
          type: array
          items:
            $ref: "#/components/schemas/Param"
          example:
            - name: "threshold"
              value: "3"
      required:
        - monitor_id
        - trigger_id
        - trigger_name
        - trigger_condition

    Triggers:
      description: List of Trigger objects
      type: array
      items:
        $ref: "#/components/schemas/Trigger"

    Param:
      description: Generic name, value pair for parameters or settings.
      type: object

      properties:
        name:
          description: Name of parameter.
          type: string
          example: "parameter_name"
        value:
          description: Value of parameter.
          type: string
          example: "parameter_value_string"

    Error:
      description: "Error response {TBD: fill out}"
      type: object
      properties:
        reason:
          type: string
          description: Detailed reason for error.
          example: "Invalid user input in parameter..(etc.)"

    Occupant:
      description: A person in the scene.
      type: object
      properties:
        bounding_box:
          $ref: "#/components/schemas/BoundingBox"
        person_id:
          description: ID of the person
          type: string
          example: "0"
        dwell_time:
          description: How long the person has been dwelling
          type: number
          example: 60000

    OccupancyCount:
      description: Occupancy Count
      type: object
      properties:
        min:
          type: integer
          example: 0
        max:
          type: integer
          example: 26
        average:
          type: integer
          example: 8

    OccupancyHeatmap:
      description: Occupancy Heatmap
      type: object
      properties:
        rows:
          type: integer
          example: 64
        cols:
          type: integer
          example: 64
        data:
          type: array
          items:
            type: array
            items:
              type: integer
            minItems: 64
            maxItems: 64
          minItems: 64
          maxItems: 64

  examples:

    triggerExampleRequiredAccessories:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Person lacking helmet, goggles, or gloves"
        trigger_condition: "required_accessories"
        params:
          - name: "accessories"
            value: "helmet, goggles, glove"

    triggerExampleRestrictedAccessories:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Person with restricted equipment"
        trigger_condition: "restricted_accessories"
        params:
          - name: "accessories"
            value: "cellphone"

    triggerOccupancyOver:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Trigger an alert whenever occupancy changes from <= 2 to >= 3."
        trigger_condition: "occupancy_over"
        params:
          - name: "threshold"
            value: "2"

    triggerOccupancyUnder:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Trigger an alert whenever occupancy changes from >= 3 to <= 2."
        trigger_condition: "occupancy_under"
        params:
          - name: "threshold"
            value: "3"

    triggerOccupancyChanged:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Alert each time occupancy changes in frame; no params needed."
        trigger_condition: "occupancy_changed"

    triggerLoiteringOver:
      value:
        monitor_id: *MONITOR_EXAMPLE
        trigger_id: *TRIGGER_ID_EXAMPLE
        trigger_name: "Occupant has been loitering for more than 5 minutes."
        trigger_condition: "loitering_over"
        params:
          - name: "threshold"
            value: "300000"